# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/soumy/game1/game1.runs/synth_1/vga_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param checkpoint.writeSynthRtdsInDcp 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/soumy/game1/game1.cache/wt [current_project]
set_property parent.project_path C:/Users/soumy/game1/game1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/soumy/Downloads/RD_hdmi_ip2020 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/soumy/game1/game1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/soumy/OneDrive/Desktop/clut__choumya.coe
add_files C:/Users/soumy/OneDrive/Desktop/choumya_128x480__.coe
add_files C:/Users/soumy/OneDrive/Desktop/monochrome_128x32_romstyle.coe
add_files C:/Users/soumy/OneDrive/Desktop/ball.coe
add_files c:/Users/soumy/OneDrive/Desktop/zero_coe.coe
add_files c:/Users/soumy/OneDrive/Desktop/one_coe.coe
add_files c:/Users/soumy/OneDrive/Desktop/two_coe.coe
add_files c:/Users/soumy/OneDrive/Desktop/three.coe
add_files c:/Users/soumy/OneDrive/Desktop/four.coe
add_files c:/Users/soumy/OneDrive/Desktop/five.coe
add_files c:/Users/soumy/OneDrive/Desktop/six.coe
add_files c:/Users/soumy/OneDrive/Desktop/seven.coe
add_files c:/Users/soumy/OneDrive/Desktop/eight1.coe
add_files c:/Users/soumy/OneDrive/Desktop/nine1.coe
add_files c:/Users/soumy/OneDrive/Desktop/new_t.coe
add_files c:/Users/soumy/OneDrive/Desktop/gameover.coe
read_verilog -library xil_defaultlib {
  C:/Users/soumy/game1/game1.srcs/sources_1/new/number_list.v
  C:/Users/soumy/game1/game1.srcs/sources_1/new/rgb_val.v
  C:/Users/soumy/game1/game1.srcs/sources_1/new/simple_counter.v
  C:/Users/soumy/game1/game1.srcs/sources_1/new/vga1.v
  C:/Users/soumy/game1/game1.srcs/sources_1/new/vga_wrapper.v
}
read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_15_1/blk_mem_gen_15.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_15_1/blk_mem_gen_15_ooc.xdc]

read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_14/blk_mem_gen_14.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_14/blk_mem_gen_14_ooc.xdc]

read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_2_1/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_2_1/blk_mem_gen_2_ooc.xdc]

read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_13/blk_mem_gen_13.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_13/blk_mem_gen_13_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_12/blk_mem_gen_12.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_12/blk_mem_gen_12_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_9/blk_mem_gen_9_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet c:/Users/soumy/game1/game1.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet C:/Users/soumy/game1/game1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/soumy/game1/game1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/soumy/game1/game1.srcs/constrs_1/new/game1.xdc
set_property used_in_implementation false [get_files C:/Users/soumy/game1/game1.srcs/constrs_1/new/game1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/soumy/game1/game1.srcs/utils_1/imports/synth_1/vga_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top vga_wrapper -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file vga_wrapper_utilization_synth.rpt -pb vga_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
