set_property SRC_FILE_INFO {cfile:C:/Users/soumy/project_3/project_3.srcs/constrs_1/new/music.xdc rfile:../../../project_3.srcs/constrs_1/new/music.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports buzzer]
